insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(5,1,'CPU Intel Core i9-9900K',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(16,1,'CPU AMD Ryzen Threadripper 1920X',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(4,2,'Mainboard MSI MEG X399 CREATION',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(3,2,'Mainboard GIGABYTE Z390 DESIGNARE',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(2,2,'Mainboard ASUS ROG Strix Z390-F Gaming',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(10,3,'RAM G.SKILL TridentZ RGB 2x16GB DDR4 3000MHz',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(11,3,'RAM laptop Kingston (1x16GB) DDR4 2400MHz',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(6,3,'RAM desktop CORSAIR Vengeance (2x8GB) DDR4 2400MHz',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(2,4,N'Card màn hình ASUS GeForce RTX 2080Ti 11GB GDDR6 DUAL OC',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(3,4,N'Card màn hình GIGABYTE GeForce RTX 2080Ti 11GB GDDR6 AORUS Xtreme',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(4,4,N'Card màn hình MSI GeForce RTX 2080Ti 11GB GDDR6 VENTUS',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(6,5,N'Nguồn máy tính CORSAIR CX750M - 750W - 80 Plus Bronze - Semi Modular',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(17,5,N'Nguồn máy tính Cooler Master MWE Gold 750 - 750W - 80 Plus Gold - Full Modular',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(17,6,N'Case máy tính Cooler Master Cosmos C700P',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(17,11,N'Tản nước AIO Cooler Master MASTERLIQUID ML240R RGB',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(6,11,N'Quạt CORSAIR LL120 RGB 120mm (3fan + Lighting node Pro)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(5,7,N'Ổ cứng SSD Intel Optane 32GB M.2 NVMe',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(13,7,N'Ổ cứng SSD Samsung 970 Pro 512GB M.2 2280 NVMe',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(11,7,N'Ổ cứng SSD Kingston 480GB 2.5" SATA 3',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(5,7,N'Ổ cứng SSD Intel 540s 360GB 2.5" SATA 3',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(3,7,N'Ổ cứng SSD GIGABYTE AORUS RGB M.2 NVMe SSD 256GB 256GB M.2 2280 NVMe',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(18,8,N'Màn Hình Acer 27" XB271H (1920x1080/TN/144Hz/1ms/G-Sync)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(2,8,N'Màn Hình ASUS ROG Swift 27" PG279Q (2560x1440/IPS/165Hz/4ms/G-Sync)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(19,8,N'Màn Hình BenQ Zowie 24.5" XL2546 (1920x1080/TN/240Hz/1ms)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(12,8,N'Màn Hình Dell Ultrasharp 27" U2718Q (3840x2160/IPS/60Hz/5ms)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(14,8,N'Màn Hình HP 24" Z24n G2 (1JS09A4) (1920x1200/IPS/60Hz/5ms)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(20,8,N'Màn Hình Lenovo 27" L27i-28 (1920x1080/IPS/75Hz/4ms/FreeSync)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(15,8,N'Màn Hình LG 27" 27MD5KA-B (5120x2880/IPS/60Hz/12ms)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(4,8,N'Màn Hình MSI Optix 32" AG32C (1920x1080/VA/165Hz/1ms/FreeSync)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(13,8,N'Màn Hình cong Samsung 34" LC34J791WTEXXV (3440x1440/VA/100Hz/4ms/FreeSync)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(1,9,N'Chuột không dây Logitech G903',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(6,9,N'Chuột máy tính Corsair Glaive RGB Aluminum',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(7,9,N'Chuột không dây Razer Mamba Wireless',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(8,9,N'Chuột không dây SteelSeries Rival 650 Wireless',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(9,9,N'Chuột Fuhlen G90 Pro 5000 DPI Infrared USB Led RGB',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(1,10,N'Bàn phím cơ Logitech Gaming G512 (Full size /Romer-G Tactile)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(6,10,N'Bàn phím cơ CORSAIR K95 Platinum (Full size/Cherry MX Speed Brown/RGB)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(7,10,N'Bàn phím cơ Razer BlackWidow Elite (Full size/Razer Green/RGB)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(9,10,N'Bàn phím cơ Fuhlen Destroyer (Full size/Optical Switch/7 màu)',50);
insert into Products(ProducerID, CategoryID, Ten, SoLuong) values(21,10,N'Bàn phím cơ Dareu DK1280 RGB (Full size/Brown D switch/RGB)',50);