SET IDENTITY_INSERT [dbo].[Producers] ON
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (1, N'Logitech')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (2, N'ASUS')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (3, N'Gigabyte')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (4, N'MSI')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (5, N'Intel')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (6, N'Corsair')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (7, N'Razer')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (8, N'SteelSeries')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (9, N'Fuhlen')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (10, N'G.SKill')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (11, N'Kingston')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (12, N'Dell')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (13, N'Samsung')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (14, N'HP')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (15, N'LG')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (16, N'AMD')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (17, N'Cooler Master')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (18, N'Acer')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (19, N'BenQ')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (20, N'Lenovo')
INSERT INTO [dbo].[Producers] ([ID], [Ten]) VALUES (21, N'DareU')
SET IDENTITY_INSERT [dbo].[Producers] OFF
